### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by wolftune** [makaroni4/guitar_bro#2]
I suggest AGPL as this is a web app. But anything compatible is acceptable enough, see http://www.choosealicense.org if you're not sure about license issues.

**Comment by makaroni4** [comment]
@wolftune thanks a lot for suggestion, I went with MIT since it's the easiest + I'd love to see people contributing and improving the project

**Comment by wolftune** [comment]
Thanks! I can appreciate MIT from a [Copyfree](http://copyfree.org/) perspective. I do hope people don't get the idea that AGPL is in any way non-easy or less-welcoming for contributions though. Cheers
