### ISSUE TITLE
typo "hightest"

### ISSUE THREAD

**Issue by wolftune** [makaroni4/guitar_bro#3]
there's a 'highest' string but no 'hightest'.

Regardless, a better term would be "thinnest" and "thickest" so it doesn't get the confusion people have over the metaphor of "high sound" vs string-closest-to-the-ceiling. Otherwise, "first string" is the standard guitar term.

**Comment by makaroni4** [comment]
Thanks a lot, @wolftune, brilliant suggestion 🚀 

Fixed here: https://github.com/makaroni4/guitar_bro/commit/9d3db71aabec4d855346e56b6ce9509579f4f420
